-- Translate the APC distribution string into granular booleans
-- that can be combined at the next level up into useful logical asswertions
-- like continental-native (aka mainland-native) etc
--
-- Depends on taxon_mv.


drop view if exists dist_granular_booleans_v;

create view dist_granular_booleans_v as 
select taxon_mv.*,
       (taxon_distribution ~ 'ACT,' or taxon_distribution ~ 'ACT$') act_unqualified_native,
       (taxon_distribution ~ 'NSW,' or taxon_distribution ~ 'NSW$') nsw_unqualified_native,
       (taxon_distribution ~ 'NT,' or taxon_distribution ~ 'NT$') nt_unqualified_native,
       (taxon_distribution ~ 'Qld,' or taxon_distribution ~ 'Qld$') qld_unqualified_native,
       (taxon_distribution ~ 'SA,' or taxon_distribution ~ 'SA$') sa_unqualified_native,
       (taxon_distribution ~ 'Tas,' or taxon_distribution ~ 'Tas$') tas_unqualified_native,
       (taxon_distribution ~ 'Vic,' or taxon_distribution ~ 'Vic$') vic_unqualified_native,
       (taxon_distribution ~ 'WA,' or taxon_distribution ~ 'WA$') wa_unqualified_native,
       (taxon_distribution ~ 'AR,' or taxon_distribution ~ 'AR$') ar_unqualified_native,
       (taxon_distribution ~ 'LHI,' or taxon_distribution ~ 'LHI$') lhi_unqualified_native,
       (taxon_distribution ~ 'ChI,' or taxon_distribution ~ 'ChI$') chi_unqualified_native,
       (taxon_distribution ~ 'CaI,' or taxon_distribution ~ 'CaI$') cai_unqualified_native,
       (taxon_distribution ~ 'CSI,' or taxon_distribution ~ 'CSI$') csi_unqualified_native,
       (taxon_distribution ~ 'CoI,' or taxon_distribution ~ 'CoI$') coi_unqualified_native,
       (taxon_distribution ~ 'HI,' or taxon_distribution ~ 'HI$') hi_unqualified_native,
       (taxon_distribution ~ 'MDI,' or taxon_distribution ~ 'MDI$') mdi_unqualified_native,
       (taxon_distribution ~ 'MI,' or taxon_distribution ~ 'MI$') mi_unqualified_native,
       (taxon_distribution ~ 'NI,' or taxon_distribution ~ 'NI$') ni_unqualified_native,
       taxon_distribution ~ 'ACT \(naturalised\)' act_naturalised,
       taxon_distribution ~ 'NSW \(naturalised\)' nsw_naturalised,
       taxon_distribution ~ 'NT \(naturalised\)' nt_naturalised,
       taxon_distribution ~ 'Qld \(naturalised\)' qld_naturalised,
       taxon_distribution ~ 'SA \(naturalised\)' sa_naturalised,
       taxon_distribution ~ 'Tas \(naturalised\)' tas_naturalised,
       taxon_distribution ~ 'Vic \(naturalised\)' vic_naturalised,
       taxon_distribution ~ 'WA \(naturalised\)' wa_naturalised,
       taxon_distribution ~ 'ACT \(doubtfully naturalised\)' act_doubtfully_naturalised,
       taxon_distribution ~ 'NSW \(doubtfully naturalised\)' nsw_doubtfully_naturalised,
       taxon_distribution ~ 'NT \(doubtfully naturalised\)' nt_doubtfully_naturalised,
       taxon_distribution ~ 'Qld \(doubtfully naturalised\)' qld_doubtfully_naturalised,
       taxon_distribution ~ 'SA \(doubtfully naturalised\)' sa_doubtfully_naturalised,
       taxon_distribution ~ 'Tas \(doubtfully naturalised\)' tas_doubtfully_naturalised,
       taxon_distribution ~ 'Vic \(doubtfully naturalised\)' vic_doubtfully_naturalised,
       taxon_distribution ~ 'WA \(doubtfully naturalised\)' wa_doubtfully_naturalised,
       taxon_distribution ~ 'ACT \(formerly naturalised\)' act_formerly_naturalised,
       taxon_distribution ~ 'NSW \(formerly naturalised\)' nsw_formerly_naturalised,
       taxon_distribution ~ 'NT \(formerly naturalised\)' nt_formerly_naturalised,
       taxon_distribution ~ 'Qld \(formerly naturalised\)' qld_formerly_naturalised,
       taxon_distribution ~ 'SA \(formerly naturalised\)' sa_formerly_naturalised,
       taxon_distribution ~ 'Tas \(formerly naturalised\)' tas_formerly_naturalised,
       taxon_distribution ~ 'Vic \(formerly naturalised\)' vic_formerly_naturalised,
       taxon_distribution ~ 'WA \(formerly naturalised\)' wa_formerly_naturalised,
       taxon_distribution ~ 'ACT \(native and naturalised\)' act_native_and_naturalised,
       taxon_distribution ~ 'NSW \(native and naturalised\)' nsw_native_and_naturalised,
       taxon_distribution ~ 'NT \(native and naturalised\)' nt_native_and_naturalised,
       taxon_distribution ~ 'Qld \(native and naturalised\)' qld_native_and_naturalised,
       taxon_distribution ~ 'SA \(native and naturalised\)' sa_native_and_naturalised,
       taxon_distribution ~ 'Tas \(native and naturalised\)' tas_native_and_naturalised,
       taxon_distribution ~ 'Vic \(native and naturalised\)' vic_native_and_naturalised,
       taxon_distribution ~ 'WA \(native and naturalised\)' wa_native_and_naturalised,
       taxon_distribution ~ 'ACT \(native and doubtfully naturalised\)' act_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'NSW \(native and doubtfully naturalised\)' nsw_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'NT \(native and doubtfully naturalised\)' nt_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'Qld \(native and doubtfully naturalised\)' qld_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'SA \(native and doubtfully naturalised\)' sa_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'Tas \(native and doubtfully naturalised\)' tas_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'Vic \(native and doubtfully naturalised\)' vic_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'WA \(native and doubtfully naturalised\)' wa_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'ACT \(native and formerly naturalised\)' act_native_and_formerly_naturalised,
       taxon_distribution ~ 'NSW \(native and formerly naturalised\)' nsw_native_and_formerly_naturalised,
       taxon_distribution ~ 'NT \(native and formerly naturalised\)' nt_native_and_formerly_naturalised,
       taxon_distribution ~ 'Qld \(native and formerly naturalised\)' qld_native_and_formerly_naturalised,
       taxon_distribution ~ 'SA \(native and formerly naturalised\)' sa_native_and_formerly_naturalised,
       taxon_distribution ~ 'Tas \(native and formerly naturalised\)' tas_native_and_formerly_naturalised,
       taxon_distribution ~ 'Vic \(native and formerly naturalised\)' vic_native_and_formerly_naturalised,
       taxon_distribution ~ 'WA \(native and formerly naturalised\)' wa_native_and_formerly_naturalised,
       taxon_distribution ~ 'ACT \(native and naturalised and uncertain origin\)' act_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NSW \(native and naturalised and uncertain origin\)' nsw_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NT \(native and naturalised and uncertain origin\)' nt_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Qld \(native and naturalised and uncertain origin\)' qld_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'SA \(native and naturalised and uncertain origin\)' sa_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Tas \(native and naturalised and uncertain origin\)' tas_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Vic \(native and naturalised and uncertain origin\)' vic_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'WA \(native and naturalised and uncertain origin\)' wa_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'ACT \(native and doubtfully naturalised and uncertain origin\)' act_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NSW \(native and doubtfully naturalised and uncertain origin\)' nsw_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NT \(native and doubtfully naturalised and uncertain origin\)' nt_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Qld \(native and doubtfully naturalised and uncertain origin\)' qld_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'SA \(native and doubtfully naturalised and uncertain origin\)' sa_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Tas \(native and doubtfully naturalised and uncertain origin\)' tas_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Vic \(native and doubtfully naturalised and uncertain origin\)' vic_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'WA \(native and doubtfully naturalised and uncertain origin\)' wa_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'ACT \(native and uncertain origin\)' act_native_and_uncertain_origin,
       taxon_distribution ~ 'NSW \(native and uncertain origin\)' nsw_native_and_uncertain_origin,
       taxon_distribution ~ 'NT \(native and uncertain origin\)' nt_native_and_uncertain_origin,
       taxon_distribution ~ 'Qld \(native and uncertain origin\)' qld_native_and_uncertain_origin,
       taxon_distribution ~ 'SA \(native and uncertain origin\)' sa_native_and_uncertain_origin,
       taxon_distribution ~ 'Tas \(native and uncertain origin\)' tas_native_and_uncertain_origin,
       taxon_distribution ~ 'Vic \(native and uncertain origin\)' vic_native_and_uncertain_origin,
       taxon_distribution ~ 'WA \(native and uncertain origin\)' wa_native_and_uncertain_origin,
       taxon_distribution ~ 'ACT \(naturalised and uncertain origin\)' act_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NSW \(naturalised and uncertain origin\)' nsw_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NT \(naturalised and uncertain origin\)' nt_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Qld \(naturalised and uncertain origin\)' qld_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'SA \(naturalised and uncertain origin\)' sa_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Tas \(naturalised and uncertain origin\)' tas_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'Vic \(naturalised and uncertain origin\)' vic_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'WA \(naturalised and uncertain origin\)' wa_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'ACT \(presumed extinct\)' act_presumed_extinct,
       taxon_distribution ~ 'NSW \(presumed extinct\)' nsw_presumed_extinct,
       taxon_distribution ~ 'NT \(presumed extinct\)' nt_presumed_extinct,
       taxon_distribution ~ 'Qld \(presumed extinct\)' qld_presumed_extinct,
       taxon_distribution ~ 'SA \(presumed extinct\)' sa_presumed_extinct,
       taxon_distribution ~ 'Tas \(presumed extinct\)' tas_presumed_extinct,
       taxon_distribution ~ 'Vic \(presumed extinct\)' vic_presumed_extinct,
       taxon_distribution ~ 'WA \(presumed extinct\)' wa_presumed_extinct,
       taxon_distribution ~ 'ACT \(uncertain origin\)' act_uncertain_origin,
       taxon_distribution ~ 'NSW \(uncertain origin\)' nsw_uncertain_origin,
       taxon_distribution ~ 'NT \(uncertain origin\)' nt_uncertain_origin,
       taxon_distribution ~ 'Qld \(uncertain origin\)' qld_uncertain_origin,
       taxon_distribution ~ 'SA \(uncertain origin\)' sa_uncertain_origin,
       taxon_distribution ~ 'Tas \(uncertain origin\)' tas_uncertain_origin,
       taxon_distribution ~ 'Vic \(uncertain origin\)' vic_uncertain_origin,
       taxon_distribution ~ 'WA \(uncertain origin\)' wa_uncertain_origin,
       taxon_distribution ~ 'AR \(naturalised\)' ar_naturalised,
       taxon_distribution ~ 'ChI \(naturalised\)' chi_naturalised,
       taxon_distribution ~ 'CaI \(naturalised\)' cai_naturalised,
       taxon_distribution ~ 'CoI \(naturalised\)' coi_naturalised,
       taxon_distribution ~ 'CSI \(naturalised\)' csi_naturalised,
       taxon_distribution ~ 'HI \(naturalised\)' hi_naturalised,
       taxon_distribution ~ 'LHI \(naturalised\)' lhi_naturalised,
       taxon_distribution ~ 'MDI \(naturalised\)' mdi_naturalised,
       taxon_distribution ~ 'MI \(naturalised\)' mi_naturalised,
       taxon_distribution ~ 'NI \(naturalised\)' ni_naturalised,
       taxon_distribution ~ 'AR \(doubtfully naturalised\)' ar_doubtfully_naturalised,
       taxon_distribution ~ 'ChI \(doubtfully naturalised\)' chi_doubtfully_naturalised,
       taxon_distribution ~ 'CaI \(doubtfully naturalised\)' cai_doubtfully_naturalised,
       taxon_distribution ~ 'CoI \(doubtfully naturalised\)' coi_doubtfully_naturalised,
       taxon_distribution ~ 'CSI \(doubtfully naturalised\)' csi_doubtfully_naturalised,
       taxon_distribution ~ 'HI \(doubtfully naturalised\)' hi_doubtfully_naturalised,
       taxon_distribution ~ 'LHI \(doubtfully naturalised\)' lhi_doubtfully_naturalised,
       taxon_distribution ~ 'MDI \(doubtfully naturalised\)' mdi_doubtfully_naturalised,
       taxon_distribution ~ 'MI \(doubtfully naturalised\)' mi_doubtfully_naturalised,
       taxon_distribution ~ 'NI \(doubtfully naturalised\)' ni_doubtfully_naturalised,
       taxon_distribution ~ 'AR \(formerly naturalised\)' ar_formerly_naturalised,
       taxon_distribution ~ 'ChI \(formerly naturalised\)' chi_formerly_naturalised,
       taxon_distribution ~ 'CaI \(formerly naturalised\)' cai_formerly_naturalised,
       taxon_distribution ~ 'CoI \(formerly naturalised\)' coi_formerly_naturalised,
       taxon_distribution ~ 'CSI \(formerly naturalised\)' csi_formerly_naturalised,
       taxon_distribution ~ 'HI \(formerly naturalised\)' hi_formerly_naturalised,
       taxon_distribution ~ 'LHI \(formerly naturalised\)' lhi_formerly_naturalised,
       taxon_distribution ~ 'MDI \(formerly naturalised\)' mdi_formerly_naturalised,
       taxon_distribution ~ 'MI \(formerly naturalised\)' mi_formerly_naturalised,
       taxon_distribution ~ 'NI \(formerly naturalised\)' ni_formerly_naturalised,
       taxon_distribution ~ 'AR \(native and naturalised\)' ar_native_and_naturalised,
       taxon_distribution ~ 'ChI \(native and naturalised\)' chi_native_and_naturalised,
       taxon_distribution ~ 'CaI \(native and naturalised\)' cai_native_and_naturalised,
       taxon_distribution ~ 'CoI \(native and naturalised\)' coi_native_and_naturalised,
       taxon_distribution ~ 'CSI \(native and naturalised\)' csi_native_and_naturalised,
       taxon_distribution ~ 'HI \(native and naturalised\)' hi_native_and_naturalised,
       taxon_distribution ~ 'LHI \(native and naturalised\)' lhi_native_and_naturalised,
       taxon_distribution ~ 'MDI \(native and naturalised\)' mdi_native_and_naturalised,
       taxon_distribution ~ 'MI \(native and naturalised\)' mi_native_and_naturalised,
       taxon_distribution ~ 'NI \(native and naturalised\)' ni_native_and_naturalised,
       taxon_distribution ~ 'AR \(native and doubtfully naturalised\)' ar_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'ChI \(native and doubtfully naturalised\)' chi_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'CaI \(native and doubtfully naturalised\)' cai_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'CoI \(native and doubtfully naturalised\)' coi_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'CSI \(native and doubtfully naturalised\)' csi_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'HI \(native and doubtfully naturalised\)' hi_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'LHI \(native and doubtfully naturalised\)' lhi_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'MDI \(native and doubtfully naturalised\)' mdi_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'MI \(native and doubtfully naturalised\)' mi_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'NI \(native and doubtfully naturalised\)' ni_native_and_doubtfully_naturalised,
       taxon_distribution ~ 'AR \(native and doubtfully naturalised and uncertain origin\)' ar_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'ChI \(native and doubtfully naturalised and uncertain origin\)' chi_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CaI \(native and doubtfully naturalised and uncertain origin\)' cai_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CoI \(native and doubtfully naturalised and uncertain origin\)' coi_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CSI \(native and doubtfully naturalised and uncertain origin\)' csi_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'HI \(native and doubtfully naturalised and uncertain origin\)' hi_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'LHI \(native and doubtfully naturalised and uncertain origin\)' lhi_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'MDI \(native and doubtfully naturalised and uncertain origin\)' mdi_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'MI \(native and doubtfully naturalised and uncertain origin\)' mi_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NI \(native and doubtfully naturalised and uncertain origin\)' ni_native_and_doubtfully_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'AR \(native and formerly naturalised\)' ar_native_and_formerly_naturalised,
       taxon_distribution ~ 'ChI \(native and formerly naturalised\)' chi_native_and_formerly_naturalised,
       taxon_distribution ~ 'CaI \(native and formerly naturalised\)' cai_native_and_formerly_naturalised,
       taxon_distribution ~ 'CoI \(native and formerly naturalised\)' coi_native_and_formerly_naturalised,
       taxon_distribution ~ 'CSI \(native and formerly naturalised\)' csi_native_and_formerly_naturalised,
       taxon_distribution ~ 'HI \(native and formerly naturalised\)' hi_native_and_formerly_naturalised,
       taxon_distribution ~ 'LHI \(native and formerly naturalised\)' lhi_native_and_formerly_naturalised,
       taxon_distribution ~ 'MDI \(native and formerly naturalised\)' mdi_native_and_formerly_naturalised,
       taxon_distribution ~ 'MI \(native and formerly naturalised\)' mi_native_and_formerly_naturalised,
       taxon_distribution ~ 'NI \(native and formerly naturalised\)' ni_native_and_formerly_naturalised,
       taxon_distribution ~ 'AR \(native and naturalised and uncertain origin\)' ar_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'ChI \(native and naturalised and uncertain origin\)' chi_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CaI \(native and naturalised and uncertain origin\)' cai_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CoI \(native and naturalised and uncertain origin\)' coi_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CSI \(native and naturalised and uncertain origin\)' csi_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'HI \(native and naturalised and uncertain origin\)' hi_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'LHI \(native and naturalised and uncertain origin\)' lhi_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'MDI \(native and naturalised and uncertain origin\)' mdi_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'MI \(native and naturalised and uncertain origin\)' mi_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NI \(native and naturalised and uncertain origin\)' ni_native_and_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'AR \(native and uncertain origin\)' ar_native_and_uncertain_origin,
       taxon_distribution ~ 'ChI \(native and uncertain origin\)' chi_native_and_uncertain_origin,
       taxon_distribution ~ 'CaI \(native and uncertain origin\)' cai_native_and_uncertain_origin,
       taxon_distribution ~ 'CoI \(native and uncertain origin\)' coi_native_and_uncertain_origin,
       taxon_distribution ~ 'CSI \(native and uncertain origin\)' csi_native_and_uncertain_origin,
       taxon_distribution ~ 'HI \(native and uncertain origin\)' hi_native_and_uncertain_origin,
       taxon_distribution ~ 'LHI \(native and uncertain origin\)' lhi_native_and_uncertain_origin,
       taxon_distribution ~ 'MDI \(native and uncertain origin\)' mdi_native_and_uncertain_origin,
       taxon_distribution ~ 'MI \(native and uncertain origin\)' mi_native_and_uncertain_origin,
       taxon_distribution ~ 'NI \(native and uncertain origin\)' ni_native_and_uncertain_origin,
       taxon_distribution ~ 'AR \(naturalised and uncertain origin\)' ar_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'ChI \(naturalised and uncertain origin\)' chi_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CaI \(naturalised and uncertain origin\)' cai_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CoI \(naturalised and uncertain origin\)' coi_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'CSI \(naturalised and uncertain origin\)' csi_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'HI \(naturalised and uncertain origin\)' hi_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'LHI \(naturalised and uncertain origin\)' lhi_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'MDI \(naturalised and uncertain origin\)' mdi_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'MI \(naturalised and uncertain origin\)' mi_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'NI \(naturalised and uncertain origin\)' ni_naturalised_and_uncertain_origin,
       taxon_distribution ~ 'AR \(presumed extinct\)' ar_presumed_extinct,
       taxon_distribution ~ 'ChI \(presumed extinct\)' chi_presumed_extinct,
       taxon_distribution ~ 'CaI \(presumed extinct\)' cai_presumed_extinct,
       taxon_distribution ~ 'CoI \(presumed extinct\)' coi_presumed_extinct,
       taxon_distribution ~ 'CSI \(presumed extinct\)' csi_presumed_extinct,
       taxon_distribution ~ 'HI \(presumed extinct\)' hi_presumed_extinct,
       taxon_distribution ~ 'LHI \(presumed extinct\)' lhi_presumed_extinct,
       taxon_distribution ~ 'MDI \(presumed extinct\)' mdi_presumed_extinct,
       taxon_distribution ~ 'MI \(presumed extinct\)' mi_presumed_extinct,
       taxon_distribution ~ 'NI \(presumed extinct\)' ni_presumed_extinct,
       taxon_distribution ~ 'AR \(uncertain origin\)' ar_uncertain_origin,
       taxon_distribution ~ 'ChI \(uncertain origin\)' chi_uncertain_origin,
       taxon_distribution ~ 'CaI \(uncertain origin\)' cai_uncertain_origin,
       taxon_distribution ~ 'CoI \(uncertain origin\)' coi_uncertain_origin,
       taxon_distribution ~ 'CSI \(uncertain origin\)' csi_uncertain_origin,
       taxon_distribution ~ 'HI \(uncertain origin\)' hi_uncertain_origin,
       taxon_distribution ~ 'LHI \(uncertain origin\)' lhi_uncertain_origin,
       taxon_distribution ~ 'MDI \(uncertain origin\)' mdi_uncertain_origin,
       taxon_distribution ~ 'MI \(uncertain origin\)' mi_uncertain_origin,
       taxon_distribution ~ 'NI \(uncertain origin\)' ni_uncertain_origin
  from taxon_mv
 where taxonomic_status = 'accepted'
;

